import type { Metadata } from "next";
import { headers } from "next/headers";
import Script from "next/script";
import { Inter, JetBrains_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";

import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

async function getSenderFromUrl() {
  const headersList = await headers();
  const url = headersList.get("x-url") ?? "";
  try {
    const urlObj = new URL(url);
    const sender = urlObj.searchParams.get("n");
    return decodeURIComponent(sender ?? "Alguien especial");
  } catch {
    return "Alguien especial";
  }
}

export async function generateMetadata(): Promise<Metadata> {
  const sender = await getSenderFromUrl();

  return {
    title: `¡${sender} te ha enviado un mensaje sorpresa! - Año Nuevo 2025`,
    description: `¡${sender} te ha enviado un mensaje especial! 🎉✨ Ábrelo para descubrir la sorpresa.`,
    metadataBase: new URL("https://2025.felizanionuevo.lat"),
    openGraph: {
      title: `¡${sender} te ha enviado un mensaje sorpresa!`,
      description: `${sender} te ha enviado un mensaje especial de Año Nuevo 2025. 🎉✨ Ábrelo para descubrir la sorpresa.`,
      images: [
        {
          url: "/og-image.jpg",
          width: 1200,
          height: 630,
          alt: "Mensaje de Año Nuevo 2025",
        },
      ],
      locale: "es_ES",
      type: "website",
    },
    icons: {
      icon: [
        { url: "/favicon.ico" },
        { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
        { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      ],
      apple: [{ url: "/apple-touch-icon.png" }],
      other: [
        {
          url: "/android-chrome-192x192.png",
          sizes: "192x192",
          type: "image/png",
        },
        {
          url: "/android-chrome-512x512.png",
          sizes: "512x512",
          type: "image/png",
        },
      ],
    },
  };
}

// export const metadata: Metadata = {
//   title: "Feliz año nuevo 2025",
//   description: "Generated by create next app",
//   icons: {
//     // Favicon tradicional
//     icon: [
//       { url: "/favicon.ico" },
//       { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
//       { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
//     ],
//     // Apple Touch Icon
//     apple: [{ url: "/apple-touch-icon.png" }],
//     // Iconos para Android/PWA
//     other: [
//       {
//         url: "/android-chrome-192x192.png",
//         sizes: "192x192",
//         type: "image/png",
//       },
//       {
//         url: "/android-chrome-512x512.png",
//         sizes: "512x512",
//         type: "image/png",
//       },
//     ],
//   },
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1039992783289890"
          crossOrigin="anonymous"
          strategy="afterInteractive"
        />
      </head>
      <body
        className={`${inter.variable} ${jetBrainsMono.variable} antialiased`}
      >
        {children}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
